project:
  type: website
  output-dir: docs  # Change this from _site to docs

website:
  title: "di4health.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: coding.qmd
        text: Coding        
      - href: resources.qmd
        text: Resources
      - href: team.qmd
        text: Team        
      - href: book.qmd
        text: Book
    right:
      - href: https://github.com/di4health
        icon: github
format:
  html:
    theme:
      - zephyr
      - brand
    css: styles.css
    toc: true



